component:
  name: hasad
  version: 1.0.0

build:
  type: nodejs # or another language like python, java, etc.
  commands:
    - npm install
    - npm run build

run:
  commands:
    - npm start

environment:
  variables:
    - DEV_DB_URL=mongodb+srv://hasad:hasad@cluster0.86bux.mongodb.net/development?retryWrites=true&w=majority&appName=Cluster0
    - PROD_DB_URL=mongodb+srv://hasad:hasad@cluster0.86bux.mongodb.net/production?retryWrites=true&w=majority&appName=Cluster0
    - JWT_SECRET=hasad_secret_352
